/******************************************************************
 * File: alan_token.cc
 *
 * This file was automatically generated by CppCC Version 0.0.8
 * DO NOT EDIT MANUALLY
 ******************************************************************/


#include "alan_token.hh"


const int cppcc::AlanToken::eof = 0;
const int cppcc::AlanToken::ws = 1;
const int cppcc::AlanToken::eol = 2;
const int cppcc::AlanToken::EOL_COMMENT = 3;
const int cppcc::AlanToken::COMMA = 4;
const int cppcc::AlanToken::SEMICOLON = 5;
const int cppcc::AlanToken::LPAR = 6;
const int cppcc::AlanToken::RPAR = 7;
const int cppcc::AlanToken::ASSIGN = 8;
const int cppcc::AlanToken::PLUS = 9;
const int cppcc::AlanToken::MINUS = 10;
const int cppcc::AlanToken::MUL = 11;
const int cppcc::AlanToken::DIV = 12;
const int cppcc::AlanToken::MOD = 13;
const int cppcc::AlanToken::NOT = 14;
const int cppcc::AlanToken::AND = 15;
const int cppcc::AlanToken::OR = 16;
const int cppcc::AlanToken::TRUE = 17;
const int cppcc::AlanToken::FALSE = 18;
const int cppcc::AlanToken::LT = 19;
const int cppcc::AlanToken::GT = 20;
const int cppcc::AlanToken::LE = 21;
const int cppcc::AlanToken::GE = 22;
const int cppcc::AlanToken::NE = 23;
const int cppcc::AlanToken::BOOL = 24;
const int cppcc::AlanToken::INT = 25;
const int cppcc::AlanToken::FLOAT = 26;
const int cppcc::AlanToken::STRING = 27;
const int cppcc::AlanToken::MOVE = 28;
const int cppcc::AlanToken::ANIM = 29;
const int cppcc::AlanToken::SCALE = 30;
const int cppcc::AlanToken::GOTO = 31;
const int cppcc::AlanToken::GOSUB = 32;
const int cppcc::AlanToken::RETURN = 33;
const int cppcc::AlanToken::FOR = 34;
const int cppcc::AlanToken::TO = 35;
const int cppcc::AlanToken::STEP = 36;
const int cppcc::AlanToken::NEXT = 37;
const int cppcc::AlanToken::WHILE = 38;
const int cppcc::AlanToken::WEND = 39;
const int cppcc::AlanToken::IF = 40;
const int cppcc::AlanToken::ELSE = 41;
const int cppcc::AlanToken::EIF = 42;
const int cppcc::AlanToken::PAUSE = 43;
const int cppcc::AlanToken::IS = 44;
const int cppcc::AlanToken::MOVING = 45;
const int cppcc::AlanToken::ANIMATING = 46;
const int cppcc::AlanToken::SCALING = 47;
const int cppcc::AlanToken::MOUSE = 48;
const int cppcc::AlanToken::KEY = 49;
const int cppcc::AlanToken::STRLEN = 50;
const int cppcc::AlanToken::SUBSTR = 51;
const int cppcc::AlanToken::INSTR = 52;
const int cppcc::AlanToken::RAND = 53;
const int cppcc::AlanToken::RANDF = 54;
const int cppcc::AlanToken::SIN = 55;
const int cppcc::AlanToken::COS = 56;
const int cppcc::AlanToken::TAN = 57;
const int cppcc::AlanToken::EXP = 58;
const int cppcc::AlanToken::LOG = 59;
const int cppcc::AlanToken::POW = 60;
const int cppcc::AlanToken::SQRT = 61;
const int cppcc::AlanToken::ABS = 62;
const int cppcc::AlanToken::SGN = 63;
const int cppcc::AlanToken::FLOOR = 64;
const int cppcc::AlanToken::CEIL = 65;
const int cppcc::AlanToken::MIN = 66;
const int cppcc::AlanToken::MAX = 67;
const int cppcc::AlanToken::MAGICCODE = 68;
const int cppcc::AlanToken::DEC_CONSTANT = 69;
const int cppcc::AlanToken::FLOAT_CONSTANT = 70;
const int cppcc::AlanToken::STRING_LITERAL = 71;
const int cppcc::AlanToken::IDENT = 72;



/* End of file. */
