/******************************************************************
 * File: settings_token.cc
 *
 * This file was automatically generated by CppCC Version 0.0.8
 * DO NOT EDIT MANUALLY
 ******************************************************************/


#include "settings_token.hh"


const int cppcc::SettingsToken::eof = 0;
const int cppcc::SettingsToken::ws = 1;
const int cppcc::SettingsToken::eol = 2;
const int cppcc::SettingsToken::LONG_COMMENT1 = 3;
const int cppcc::SettingsToken::LONG_COMMENT2 = 4;
const int cppcc::SettingsToken::LONG_COMMENT3 = 5;
const int cppcc::SettingsToken::LONG_COMMENT4 = 6;
const int cppcc::SettingsToken::LONG_COMMENT5 = 7;
const int cppcc::SettingsToken::LONG_COMMENT = 8;
const int cppcc::SettingsToken::EOL_COMMENT = 9;
const int cppcc::SettingsToken::LBRA = 10;
const int cppcc::SettingsToken::RBRA = 11;
const int cppcc::SettingsToken::LPAR = 12;
const int cppcc::SettingsToken::RPAR = 13;
const int cppcc::SettingsToken::LSQR = 14;
const int cppcc::SettingsToken::RSQR = 15;
const int cppcc::SettingsToken::DOT = 16;
const int cppcc::SettingsToken::COMMA = 17;
const int cppcc::SettingsToken::ASSIGN = 18;
const int cppcc::SettingsToken::HEX_CONSTANT = 19;
const int cppcc::SettingsToken::DEC_CONSTANT = 20;
const int cppcc::SettingsToken::FLOAT_CONSTANT = 21;
const int cppcc::SettingsToken::STRING_LITERAL = 22;
const int cppcc::SettingsToken::YES = 23;
const int cppcc::SettingsToken::NO = 24;
const int cppcc::SettingsToken::ON = 25;
const int cppcc::SettingsToken::OFF = 26;
const int cppcc::SettingsToken::TRUE = 27;
const int cppcc::SettingsToken::FALSE = 28;
const int cppcc::SettingsToken::IDENTIFIER = 29;



/* End of file. */
