/******************************************************************
 * File: settings_token.hh
 *
 * This file was automatically generated by CppCC Version 0.0.8
 * DO NOT EDIT MANUALLY
 ******************************************************************/


#ifndef __SETTINGS_TOKEN_HH__
#define __SETTINGS_TOKEN_HH__

#include <string>
#include <sstream>

namespace cppcc
{

class Position
{
  public:
    Position () : ln(0), col(0) {}
    Position (int ln_, int col_) : ln(ln_), col(col_) {}
    Position (const Position &o) : ln(o.ln), col(o.col) {}
    
    operator std::string () const
    {
      std::ostringstream oss;
      oss << ln << ":" << col;
      return oss.str();
    }
    
    int ln, col;
};

class SettingsToken
{
  friend class SettingsScanner;
  public:
    
    SettingsToken () : _img_valid(true) {}
    SettingsToken (int id_, const std::string &_str_img_, 
              const Position &bPos_, const Position &ePos_) :
      id(id_), bPos(bPos_), ePos(ePos_), _img_valid(true), _str_img(_str_img_)
    {}
    SettingsToken (int id_, const Position &bPos_, const Position &ePos_) :
      id(id_), bPos(bPos_), ePos(ePos_), _img_valid(true)
    {}
    SettingsToken (int id_) : 
      id(id_), _img_valid(true)
    {}
    SettingsToken (const std::string &_str_img_) : 
      _img_valid(true), _str_img(_str_img_)
    { length = _str_img.length(); }
    SettingsToken (int id_, const Position &bPos_) :
      id(id_), bPos(bPos_), ePos(bPos_), _img_valid(true)
    {}
  
  public:
    int id;
    Position bPos, ePos;
    int length;
    std::string& image()
    {
      _cacheImg();
      return _str_img;
    }
  
  private:
    const char *_img_start; //points into the scanner's buffer
    bool _img_valid; //true if the string image is in sync with the buffer
    std::string _str_img; //caches the image as a string
    
    void _set (int id_, const Position &bPos_, const Position &ePos_,
               const char *_img_start_, int length_)
    {
      id = id_; bPos = bPos_; ePos = ePos_;
      _img_start = _img_start_; length = length_;
      _img_valid = false;
    }
    
    void _set (const char *_img_start_, int length_)
    {
      _img_start = _img_start_; length = length_;
      _img_valid = false;
    }
    void _cacheImg()
    {
      if (!_img_valid) {
        _str_img.assign(_img_start, length);
        _img_valid = true;
      }
    }
    
  private: // user code
  
#line 13 "settings.cg"

#line 99 "settings_token.hh"

  
   /* Token id constants: */
  public:
  
    static const int eof;
    static const int ws;
    static const int eol;
    static const int LONG_COMMENT1;
    static const int LONG_COMMENT2;
    static const int LONG_COMMENT3;
    static const int LONG_COMMENT4;
    static const int LONG_COMMENT5;
    static const int LONG_COMMENT;
    static const int EOL_COMMENT;
    static const int LBRA;
    static const int RBRA;
    static const int LPAR;
    static const int RPAR;
    static const int LSQR;
    static const int RSQR;
    static const int DOT;
    static const int COMMA;
    static const int ASSIGN;
    static const int HEX_CONSTANT;
    static const int DEC_CONSTANT;
    static const int FLOAT_CONSTANT;
    static const int STRING_LITERAL;
    static const int YES;
    static const int NO;
    static const int ON;
    static const int OFF;
    static const int TRUE;
    static const int FALSE;
    static const int IDENTIFIER;
    
}; // end of SettingsToken class


} // end namespace cppcc
#endif // ifndef __SETTINGS_TOKEN_HH__


/* End of file. */
